### PR TITLE
add macOS CI

### PR DESCRIPTION
**Pull request by tokatoka**
Add mac os runner to ci

### CODE REVIEW

**Comment by tokatoka** [comment]
It seems we have this problem http://os-tres.net/blog/2010/02/17/mac-os-x-and-task-for-pid-mach-call/
The blog explains what steps to take to make it work, but I haven't tried. (not sure it's possible to do the same steps on gh actions)

For now, I can run `tinyinst_simple` only with sudo + LLDB, else it fails to call task_for_pid()

**Comment by elbiazo** [comment]
> It seems we have this problem http://os-tres.net/blog/2010/02/17/mac-os-x-and-task-for-pid-mach-call/ The blog explains what steps to take to make it work, but I haven't tried. (not sure it's possible to do the same steps on gh actions)
> 
> For now, I can run `tinyinst_simple` only with sudo + LLDB, else it fails to call task_for_pid()

ya had to do same thing in x64 mac... Not sure how we can do that through gh action...

**Comment by tokatoka** [comment]
let's run `cargo build --release` only for now

**Comment by elbiazo** [comment]
sounds good.

**Pull request merged**
