### PR TITLE
Macos update!

### LINKED ISSUE #4: macos support
this should be pretty straight forward. update test to get built from cmake. update build.rs to auto configure compiler.

### PR DESCRIPTION
**Pull request by elbiazo**
We should be able to build this project under mac with this update.

### CODE REVIEW

**Comment by tokatoka** [comment]
Hi, nice work!

but I still have problem building this.
I get
```
toka@a tinyinst-rs % cargo build --release
   Compiling tinyinst v0.1.0 (/Users/toka/tinyinst-rs)
warning: Generating Bridge files. and building for /Users/toka/tinyinst-rs/target/release/build/tinyinst-15611e53ec155fe2/out/Tinyinst
error: could not find native static library `xed`, perhaps an -L flag is missing?

The following warnings were emitted during compilation:

warning: Generating Bridge files. and building for /Users/toka/tinyinst-rs/target/release/build/tinyinst-15611e53ec155fe2/out/Tinyinst
```
and there's no xed library when I looked into TinyInst's directory after I followed their build instruction.
Did you see this error too?

**Comment by elbiazo** [comment]
> Hi, nice work!
> 
> but I still have problem building this. I get
> 
> ```
> toka@a tinyinst-rs % cargo build --release
>    Compiling tinyinst v0.1.0 (/Users/toka/tinyinst-rs)
> warning: Generating Bridge files. and building for /Users/toka/tinyinst-rs/target/release/build/tinyinst-15611e53ec155fe2/out/Tinyinst
> error: could not find native static library `xed`, perhaps an -L flag is missing?
> 
> The following warnings were emitted during compilation:
> 
> warning: Generating Bridge files. and building for /Users/toka/tinyinst-rs/target/release/build/tinyinst-15611e53ec155fe2/out/Tinyinst
> ```
> 
> and there's no xed library when I looked into TinyInst's directory after I followed their build instruction. Did you see this error too?

No but i think if you do cargo build --release -vv, you might see that if you dont run under developer powershell or environment without msvc, xed won't compile. i tried to compile Tinyinst on regular powershell and it will give you the same result.

**Comment by elbiazo** [comment]
> Hi, nice work!
> 
> but I still have problem building this. I get
> 
> ```
> toka@a tinyinst-rs % cargo build --release
>    Compiling tinyinst v0.1.0 (/Users/toka/tinyinst-rs)
> warning: Generating Bridge files. and building for /Users/toka/tinyinst-rs/target/release/build/tinyinst-15611e53ec155fe2/out/Tinyinst
> error: could not find native static library `xed`, perhaps an -L flag is missing?
> 
> The following warnings were emitted during compilation:
> 
> warning: Generating Bridge files. and building for /Users/toka/tinyinst-rs/target/release/build/tinyinst-15611e53ec155fe2/out/Tinyinst
> ```
> 
> and there's no xed library when I looked into TinyInst's directory after I followed their build instruction. Did you see this error too?

sorry i read your question wrong. If xed isn't on third party it means it didnt `git submodule update --init --recursive` to pull down dependencies.  in rust code it is this line that is responsible for doing that https://github.com/AFLplusplus/tinyinst-rs/blob/a2a879a350940f2793b8c840e7a3fafa8c345487/build.rs#L98

**Comment by elbiazo** [comment]
> Hi, nice work!
> 
> but I still have problem building this. I get
> 
> ```
> toka@a tinyinst-rs % cargo build --release
>    Compiling tinyinst v0.1.0 (/Users/toka/tinyinst-rs)
> warning: Generating Bridge files. and building for /Users/toka/tinyinst-rs/target/release/build/tinyinst-15611e53ec155fe2/out/Tinyinst
> error: could not find native static library `xed`, perhaps an -L flag is missing?
> 
> The following warnings were emitted during compilation:
> 
> warning: Generating Bridge files. and building for /Users/toka/tinyinst-rs/target/release/build/tinyinst-15611e53ec155fe2/out/Tinyinst
> ```
> 
> and there's no xed library when I looked into TinyInst's directory after I followed their build instruction. Did you see this error too?

here are some screen shot

image
image
image

**Comment by tokatoka** [comment]
yup windows works, but on macos I can't find xed lib

**Comment by tokatoka** [comment]
Um, ok. I got it. xed is intel's xed
I'm testing this on m1mac so xed is not supposed to be there

https://github.com/googleprojectzero/TinyInst/blob/master/CMakeLists.txt#L121

**Comment by tokatoka** [comment]
Now this builds for me. 

If this change is good for you too, then let's merge
Are you developing with x64 macos btw?

**Comment by elbiazo** [comment]
> Now this builds for me. 
> 
> 
> 
> If this change is good for you too, then let's merge
> 
> Are you developing with x64 macos btw?

as long as it works on windows after the new commit i am okay with merging. And yes I was developing on x64 macos

**Comment by tokatoka** [comment]
Okay let's merge

**Pull request merged**
